### ISSUE TITLE
non-free dependencies

### ISSUE THREAD

**Issue by IzzySoft** [TheMusicmax/Musicmax#257]
I see with the latest release, Google Ads (and thus the GMS library) have been added – so I had to add the `Ads` and `NonFreeDep` anti-features to the app's listing in my repo. This also makes it impossible to get your app to F-Droid.org if you had planned that. Maybe you could provide a free/libre build flavor (and its APK) for the free/libre world? Thanks in advance for considering!

**Comment by MaximillianLeonov** [comment]
@IzzySoft,

Hi, Izzy. I want to use Google Play Services and Firebase products. You can remove my app from your repo. But thank you for taking care of it.

**Comment by IzzySoft** [comment]
That's a very unfortunate decision, Max – you'll leave everybody out who for some reason cannot or does not want to use Google Play. What makes you think those services are needed for your app? Maybe there are alternatives to it? For example, most features of Firebase are available also with free implementations like [appwrite](https://github.com/appwrite/appwrite) or [Supabase](https://supabase.com/). And I have no idea why a music app might need GMS (nor Firebase at that).

**Comment by MaximillianLeonov** [comment]
I am pretty happy with GMS and Firebase features, and I do not want to change it. I am sorry about that.

> And I have no idea why a music app might need GMS (nor Firebase at that).

Play Feature Delivery, In-App Review, In-App Update libraries, etc. Firebase Analytics, Crashlytics, Auth, Firestore.

**Comment by IzzySoft** [comment]
So all the privacy nightmares included :cry: That's your final word? Or would you consider a separate F/LOSS flavor for those who'd not use PlayStore anyway (and thus would not give in-app-reviews, would not need play delivery – and especially would not want the Google <s>crackers</s> trackers? None of that is needed for the app's functionality – but would scare away privacy-minded people.

**Comment by IzzySoft** [comment]
Sad. So for now, the 2 anti-features will stay (it's 2 libraries now). Once you add Firebase, Crashlytics etc to the mix, I'll most likely have to remove the app from my repo as it will exceed the threshold (I have only 2 eyes I can close).

Btw, you've see [this one](https://www.virustotal.com/gui/file/6a74dc25c2b54b9665f8aa5af9b90e3d6969f6accc432962620c223333bb614e/detection/f-6a74dc25c2b54b9665f8aa5af9b90e3d6969f6accc432962620c223333bb614e-1681666339) introduced with your last release? (you'll lose this "early-warning-system" (fed by the automated scans here) as well with the unlisting from my repo btw.)

**Comment by MaximillianLeonov** [comment]
I am disappointed to hear that you will be removing my app from your repo, but I understand your decision. However, I believe that Play Services and Firebase offer many valuable features that are essential for my app's functionality. Moreover, since the majority of my audience uses the Play Store, it makes sense for me to continue using these services. I appreciate your feedback and will make sure to remove the corresponding badge and link as requested.

**Comment by IzzySoft** [comment]
Well, F-Droid (and my repo as well) are about free/libre software – those libraries are not libre (just free of monetary pay). Further, it's about privacy – and Google is one of the biggest data collectors. For all the libraries in question there are FOSS replacements which would be acceptable, as pointed out – maybe with the exception of the Playstore specific ones. And our opinion on "essential" differs it seems: I do not see why any of those would be needed to play music :wink:

Be it as it might: I didn't take the decision lightly, but with the latest additions I had no choice, as I [wrote before](#issuecomment-1511510476). Further, those using my repo (which if I might say so is quite popular meanwhile) would expect me to act like I did: they expect my repo to only serve F/LOSS software that comes without or just with absolute minimal amount of non-free libs, as it's advertised. So once I become aware of an app adding those, I have to act.

Should in the future you offer the APK of a "FOSS build flavor", please let me know and I gladly add your app to my repo again (metadata were archived, so setup would be an easy task).
